name: Build DLL

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
      
      - name: Compile DLL
        run: |
          cl.exe /EHsc /LD /MT /O2 /Fe:cheat.dll dll-cs2-cheat.cpp
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cheat-dll
          path: cheat.dll
